dist: bionic

language: php

php:
  - 7.2
  - 7.3

sudo: required

before_script:
  - mkdir -p build/logs
  - sudo apt-get update
  # yaml
  - sudo apt install -y libyaml-dev
  - 'printf "\n" | pecl install yaml'
  # install apache
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default
  - cat /etc/apache2/envvars
  - find ~/.phpenv -name *.so
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo apt-get install apache2
  - sudo a2enmod rewrite actions proxy_fcgi
  - sudo sed -i -e "s/www-data/travis/g" /etc/apache2/envvars
#  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  # install php modules
  - composer require php-coveralls/php-coveralls
  - composer update

after_success:
  - php vendor/bin/php-coveralls -v

cache:
  directories:
    - vendor


