name: document

on: 
  push:
    branches:
    - master

jobs:
  document:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.4.1
      with: 
        ssh-private-key: ${{ secrets.docsRepoToken }}
    - name: install phpdocumentator
      run: curl -L https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.0.0/phpDocumentor.phar > phpdoc.phar
    - name: fetch docs repo
      run: git clone --depth 1 git@github.com:acdh-oeaw/arche-docs.git docsrepo
    - name: generate docs
      run: |
        rm -fR docsrepo/arche-core/*
        php -f phpdoc.phar run -d src -t docsrepo/arche-core
    - name: commit docs
      run: |
        cd docsrepo
        git config user.email "workflow@github.actions"
        git config user.name "Github Actions Workflow"
        git add arche-core/*
        git commit -a -m 'Documentation updated' || true
        git push origin || true
